packageExtensions:
  react-native-quick-crypto:
    dependencies:
      readable-stream: 4.5.2

patchedDependencies:
  '@react-native-voice/voice': patches/@react-native-voice__voice.patch
  react-native-tts: patches/react-native-tts.patch
