import { API_BASE_URL } from '../config';

const billingRoutes = {
  reconciliations: `${API_BASE_URL}/api/v1/billing/reconciliations/`,
  reconciliation: (id: string) => `${API_BASE_URL}/api/v1/billing/reconciliations/${id}/`,
  reconcile: (id: string) => `${API_BASE_URL}/api/v1/billing/reconciliations/${id}/reconcile/`,
  claims: `${API_BASE_URL}/api/v1/billing/claims/`,
  claim: (id: string) => `${API_BASE_URL}/api/v1/billing/claims/${id}/`,
  claimStatus: (id: string) => `${API_BASE_URL}/api/v1/billing/claims/${id}/update_status/`,
  disputes: `${API_BASE_URL}/api/v1/billing/disputes/`,
  dispute: (id: string) => `${API_BASE_URL}/api/v1/billing/disputes/${id}/`,
  disputeResolve: (id: string) => `${API_BASE_URL}/api/v1/billing/disputes/${id}/resolve/`,
  pricingInsights: `${API_BASE_URL}/api/v1/billing/pricing-insights/`,
  profitabilityEntitlements: `${API_BASE_URL}/api/v1/billing/profitability-entitlements/`,
  profitabilityCommandCenter: `${API_BASE_URL}/api/v1/billing/profitability-command-center/`,
  profitabilityLaunchGate: `${API_BASE_URL}/api/v1/billing/profitability-launch-gate/`,
  profitabilitySubscriptionLifecycle: `${API_BASE_URL}/api/v1/billing/profitability-subscription-lifecycle/`,
  profitabilityRevenueOpsEvidence: `${API_BASE_URL}/api/v1/billing/profitability-revenue-ops-evidence/`,
  profitabilityEvidenceWorkflowPlan: `${API_BASE_URL}/api/v1/billing/profitability-evidence-workflow-plan/`,
  profitabilityRevenueReadiness: `${API_BASE_URL}/api/v1/billing/profitability-revenue-readiness/`,
  profitabilityStagingProofWorkflows: `${API_BASE_URL}/api/v1/billing/profitability-staging-proof-workflows/`,
  profitabilityProductionGoNoGo: `${API_BASE_URL}/api/v1/billing/profitability-production-go-no-go/`,
  profitabilityBetaLaunchPlan: `${API_BASE_URL}/api/v1/billing/profitability-beta-launch-plan/`,
  profitabilityBetaOperations: `${API_BASE_URL}/api/v1/billing/profitability-beta-operations/`,
  revenueLaunchEvidence: `${API_BASE_URL}/api/v1/billing/revenue-launch-evidence/`,
  revenueLaunchEvidenceDetail: (id: string) => `${API_BASE_URL}/api/v1/billing/revenue-launch-evidence/${id}/`,
  revenueLaunchEvidenceSubmit: (id: string) => `${API_BASE_URL}/api/v1/billing/revenue-launch-evidence/${id}/submit/`,
  revenueLaunchEvidenceApprove: (id: string) => `${API_BASE_URL}/api/v1/billing/revenue-launch-evidence/${id}/approve/`,
  revenueLaunchEvidenceNeedsChanges: (id: string) => `${API_BASE_URL}/api/v1/billing/revenue-launch-evidence/${id}/needs-changes/`,
  revenueLaunchEvidenceReject: (id: string) => `${API_BASE_URL}/api/v1/billing/revenue-launch-evidence/${id}/reject/`,
  revenueLaunchEvidenceRevoke: (id: string) => `${API_BASE_URL}/api/v1/billing/revenue-launch-evidence/${id}/revoke/`,
  walletReceipt: `${API_BASE_URL}/api/v1/billing/wallet/receipt/`,
  walletRefund: `${API_BASE_URL}/api/v1/billing/wallet/refund/`,
  invoices: `${API_BASE_URL}/api/v1/tiers/invoices/`,
  loyalty: `${API_BASE_URL}/api/v1/commerce/loyalty/`,
  loyaltyBalance: `${API_BASE_URL}/api/v1/commerce/loyalty/balance/`,
};

export default billingRoutes;
