import { API_BASE_URL, NEST_API_BASE_URL } from '../config';

const socialRoutes = {
  content: {
    list: `${API_BASE_URL}/api/v1/contents/`,
    create: `${API_BASE_URL}/api/v1/contents/`,
    detail: (id: string) => `${API_BASE_URL}/api/v1/contents/${id}/`,
    react: (id: string) => `${API_BASE_URL}/api/v1/contents/${id}/react/`,
    metrics: (id: string) => `${API_BASE_URL}/api/v1/contents/${id}/metrics/`,
  },
  events: {
    list: `${API_BASE_URL}/api/v1/api/events/`,
    create: `${API_BASE_URL}/api/v1/api/events/`,
    detail: (id: string) => `${API_BASE_URL}/api/v1/api/events/${id}/`,
    rsvp: `${API_BASE_URL}/api/v1/api/attendances/`,
    tickets: `${API_BASE_URL}/api/v1/api/tickets/`,
  },
  notificationRules: {
    list: `${API_BASE_URL}/api/v1/notification-rules/`,
    detail: (id: string) => `${API_BASE_URL}/api/v1/notification-rules/${id}/`,
  },
  community: {
    list: `${API_BASE_URL}/api/v1/chat-communities/`,
    create: `${API_BASE_URL}/api/v1/chat-communities/`,
    detail: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/`,
    members: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/members/`,
    addMembers: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/add-members/`,
    join: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/join/`,
    leave: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/leave/`,
    requestJoin: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/request-join/`,
    approveRequest: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/approve-request/`,
    rejectRequest: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/reject-request/`,
    ban: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/ban/`,
    unban: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/unban/`,
    inviteLink: (id: string) => `${API_BASE_URL}/api/v1/chat-communities/${id}/invite-link/`,
    joinByInvite: `${API_BASE_URL}/api/v1/chat-communities/join-by-invite/`,
    posts: `${API_BASE_URL}/api/v1/posts/`,
    postDetail: (id: string) => `${API_BASE_URL}/api/v1/posts/${id}/`,
    postComment: (id: string) => `${API_BASE_URL}/api/v1/posts/${id}/comment/`,
    postComments: (id: string) => `${API_BASE_URL}/api/v1/posts/${id}/comments/`,
    postCommentRoom: (id: string) => `${API_BASE_URL}/api/v1/posts/${id}/comment-room/`,
    postReact: (id: string) => `${API_BASE_URL}/api/v1/posts/${id}/react/`,
    postPin: (id: string) => `${API_BASE_URL}/api/v1/posts/${id}/pin/`,
    postUnpin: (id: string) => `${API_BASE_URL}/api/v1/posts/${id}/unpin/`,
    postDelete: (id: string) => `${API_BASE_URL}/api/v1/posts/${id}/delete/`,
    postBroadcast: (id: string) => `${API_BASE_URL}/api/v1/posts/${id}/broadcast/`,
  },
  groups: {
    list: `${API_BASE_URL}/api/v1/chat-groups/`,
    create: `${API_BASE_URL}/api/v1/chat-groups/`,
    detail: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/`,
    members: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/members/`,
    addMembers: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/add-members/`,
    join: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/join/`,
    joinByInvite: `${API_BASE_URL}/api/v1/chat-groups/join-by-invite/`,
    leave: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/leave/`,
    requestJoin: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/request-join/`,
    approveRequest: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/approve-request/`,
    rejectRequest: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/reject-request/`,
    ban: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/ban/`,
    unban: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/unban/`,
    inviteLink: (id: string) => `${API_BASE_URL}/api/v1/chat-groups/${id}/invite-link/`,
  },
  channels: {
    getAllChannels: `${API_BASE_URL}/api/v1/channels/`,
    getChannelById: (id: string) => `${API_BASE_URL}/api/v1/channels/${id}/`,
    createChannel: `${API_BASE_URL}/api/v1/channels/`,
    subscribeChannel: (id: string) => `${API_BASE_URL}/api/v1/channels/${id}/subscribe/`,
    addMembersToChannel: (channelId: string) => `${API_BASE_URL}/api/v1/channels/${channelId}/members/`,
    getChannelMembers: (channelId: string) => `${API_BASE_URL}/api/v1/channels/${channelId}/members/`,
  },
  subchannels: {
    getAllSubchannels: `${API_BASE_URL}/subchannels/`,
    getSubchannelById: (id: string) => `${API_BASE_URL}/subchannels/${id}/`,
    createSubchannel: `${API_BASE_URL}/subchannels/create/`,
    getSubchannelMembers: (id: string) => `${API_BASE_URL}/subchannels/${id}/members/`,
  },
  statuses: {
    list: `${API_BASE_URL}/api/v1/statuses/`,
    search: `${API_BASE_URL}/api/v1/statuses/search/`,
    create: `${API_BASE_URL}/api/v1/statuses/`,
    mine: `${API_BASE_URL}/api/v1/statuses/mine/`,
    view: (id: string) => `${API_BASE_URL}/api/v1/statuses/${id}/view/`,
    viewers: (id: string) => `${API_BASE_URL}/api/v1/statuses/${id}/viewers/`,
    report: (id: string) => `${API_BASE_URL}/api/v1/statuses/${id}/report/`,
    reply: (id: string) => `${API_BASE_URL}/api/v1/statuses/${id}/reply/`,
    mute: `${API_BASE_URL}/api/v1/statuses/mute/`,
    unmute: `${API_BASE_URL}/api/v1/statuses/unmute/`,
  },
  chat: {
    listConversations: `${API_BASE_URL}/api/v1/chats/conversations/`,
    conversationDetail: (id: string) => `${API_BASE_URL}/api/v1/chats/conversations/${id}/`,
    searchConversations: `${API_BASE_URL}/api/v1/chats/conversations/search/`,
    searchParticipants: `${API_BASE_URL}/api/v1/chats/conversations/participant-search/`,
    directConversation: `${API_BASE_URL}/api/v1/chats/conversations/direct/`,
    threads: `${API_BASE_URL}/api/v1/chats/threads/`,
    setMemberRole: (conversationId: string) =>
      `${API_BASE_URL}/api/v1/chats/conversations/${conversationId}/members/role/`,
    markRead: (conversationId: string) =>
      `${API_BASE_URL}/api/v1/chats/conversations/${conversationId}/mark-read/`,
    updateSettings: (conversationId: string) =>
      `${API_BASE_URL}/api/v1/chats/conversations/${conversationId}/settings/`,
  },
  moderation: {
    mute: `${NEST_API_BASE_URL}/moderation/mute`,
  },
  calls: {
    iceServers: `${API_BASE_URL}/api/v1/calls/ice-servers/`,
    history: `${API_BASE_URL}/api/v1/calls/history/`,
  },
  e2ee: {
    conversationKey: (conversationId: string) =>
      `${NEST_API_BASE_URL}/api/v1/e2ee/conversations/${conversationId}/key`,
  },
  stickers: {
    packs: `${API_BASE_URL}/api/v1/stickers/packs/`,
  },
};

export default socialRoutes;
