import React, { useCallback, useMemo, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useKISTheme } from '@/theme/useTheme';
import { useResponsiveLayout } from '@/theme/responsive';
import KISButton from '@/constants/KISButton';
import { getRequest } from '@/network/get';
import ROUTES from '@/network';
import type { RootStackParamList } from '@/navigation/types';

type Props = NativeStackScreenProps<RootStackParamList, 'TitheStatement'>;

type StatementEntry = {
  type: string;
  total: number;
  count: number;
};

type StatementData = {
  year: number;
  entries: StatementEntry[];
  grand_total: number;
};

const CURRENT_YEAR = new Date().getFullYear();
const YEARS = [CURRENT_YEAR, CURRENT_YEAR - 1, CURRENT_YEAR - 2, CURRENT_YEAR - 3];

const TYPE_LABELS: Record<string, string> = {
  tithe: 'Tithe',
  offering: 'Offering',
  pledge: 'Pledge',
  special: 'Special Gift',
};

export default function TitheStatementScreen({ navigation }: Props) {
  const { palette } = useKISTheme();
  const layout = useResponsiveLayout();
  const [year, setYear] = useState(CURRENT_YEAR);
  const [statement, setStatement] = useState<StatementData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const styles = useMemo(() => makeStyles(palette, layout), [palette, layout]);

  const fetchStatement = useCallback((selectedYear: number) => {
    setLoading(true);
    setError(null);
    getRequest(`${ROUTES.church.givingStatement}?year=${selectedYear}`)
      .then(res => {
        if (res?.success) setStatement(res.data ?? null);
        else setError('Could not load statement.');
      })
      .catch(() => setError('Network error.'))
      .finally(() => setLoading(false));
  }, []);

  const handleYearChange = useCallback(
    (y: number) => {
      setYear(y);
      fetchStatement(y);
    },
    [fetchStatement],
  );

  const formatCurrency = (val: number) =>
    `$${val.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;

  const handleShare = useCallback(() => {
    if (!statement) {
      Alert.alert('No data', 'Please load a statement first.');
      return;
    }
    const lines: string[] = [
      `KIS Giving Statement — ${statement.year}`,
      '──────────────────────────',
    ];
    for (const entry of statement.entries) {
      const label = TYPE_LABELS[entry.type] ?? entry.type;
      lines.push(`${label}: ${formatCurrency(entry.total)} (${entry.count} transaction${entry.count !== 1 ? 's' : ''})`);
    }
    lines.push('──────────────────────────');
    lines.push(`Total Given: ${formatCurrency(statement.grand_total)}`);
    lines.push('');
    lines.push('Generated by KIS — Kingdom Impact Systems');
    Share.share({ message: lines.join('\n'), title: `KIS Giving Statement ${statement.year}` }).catch(() => {});
  }, [statement]);

  return (
    <SafeAreaView style={styles.safe} edges={['top', 'bottom']}>
      <ScrollView contentContainerStyle={styles.scroll}>
        <Text style={styles.title}>Tithe Statement</Text>
        <Text style={styles.subtitle}>Your annual giving record for tax purposes.</Text>

        <View style={styles.yearRow}>
          {YEARS.map(y => (
            <TouchableOpacity
              key={y}
              style={[styles.yearChip, year === y && styles.yearChipActive]}
              onPress={() => handleYearChange(y)}
              hitSlop={{ top: 6, bottom: 6, left: 4, right: 4 }}
            >
              <Text style={[styles.yearChipText, year === y && styles.yearChipTextActive]}>
                {y}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        {loading && (
          <View style={styles.center}>
            <ActivityIndicator color={palette.primary} size="large" />
          </View>
        )}

        {!loading && error && (
          <View style={styles.center}>
            <Text style={styles.errorText}>{error}</Text>
            <KISButton title="Retry" onPress={() => fetchStatement(year)} style={{ marginTop: 12 }} />
          </View>
        )}

        {!loading && !error && !statement && (
          <View style={styles.center}>
            <Text style={styles.hintText}>Select a year to view your statement.</Text>
          </View>
        )}

        {!loading && !error && statement && (
          <View style={styles.statementCard}>
            <Text style={styles.statementYear}>Statement for {statement.year}</Text>

            {statement.entries.length === 0 && (
              <Text style={styles.emptyText}>No giving records for this year.</Text>
            )}

            {statement.entries.map((entry, idx) => (
              <View key={idx} style={styles.entryRow}>
                <View>
                  <Text style={styles.entryType}>
                    {TYPE_LABELS[entry.type] ?? entry.type}
                  </Text>
                  <Text style={styles.entryCount}>{entry.count} transaction{entry.count !== 1 ? 's' : ''}</Text>
                </View>
                <Text style={styles.entryTotal}>{formatCurrency(entry.total)}</Text>
              </View>
            ))}

            {statement.entries.length > 0 && (
              <View style={styles.totalRow}>
                <Text style={styles.totalLabel}>Total Given</Text>
                <Text style={styles.totalValue}>{formatCurrency(statement.grand_total)}</Text>
              </View>
            )}
          </View>
        )}

        <KISButton
          title="Share Statement"
          variant="outline"
          style={styles.downloadBtn}
          disabled={!statement}
          onPress={handleShare}
        />
      </ScrollView>
    </SafeAreaView>
  );
}

function makeStyles(palette: any, layout: any) {
  const sp = layout.pageGutter;
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: palette.bg, marginTop: 25 },
    scroll: { padding: sp, paddingBottom: 80 },
    title: { fontSize: 26, fontWeight: '700', color: palette.text, marginBottom: 6 },
    subtitle: { fontSize: 14, color: palette.subtext, marginBottom: 20 },
    yearRow: { flexDirection: 'row', gap: 8, marginBottom: 24 },
    yearChip: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.divider,
      backgroundColor: palette.surface,
      minHeight: 44,
      justifyContent: 'center',
    },
    yearChipActive: { backgroundColor: palette.primary, borderColor: palette.primary },
    yearChipText: { fontSize: 14, color: palette.text },
    yearChipTextActive: { color: palette.ivory, fontWeight: '700' },
    center: { alignItems: 'center', paddingVertical: 40 },
    errorText: { fontSize: 14, color: palette.danger, textAlign: 'center' },
    hintText: { fontSize: 14, color: palette.subtext, textAlign: 'center' },
    statementCard: {
      backgroundColor: palette.card,
      borderRadius: 14,
      padding: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: palette.divider,
      marginBottom: 20,
    },
    statementYear: {
      fontSize: 16,
      fontWeight: '700',
      color: palette.text,
      marginBottom: 14,
    },
    emptyText: { fontSize: 14, color: palette.subtext, textAlign: 'center', paddingVertical: 16 },
    entryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: palette.divider,
    },
    entryType: { fontSize: 15, fontWeight: '600', color: palette.text },
    entryCount: { fontSize: 12, color: palette.subtext, marginTop: 2 },
    entryTotal: { fontSize: 16, fontWeight: '700', color: palette.primary },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 14,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: palette.divider,
    },
    totalLabel: { fontSize: 16, fontWeight: '700', color: palette.text },
    totalValue: { fontSize: 20, fontWeight: '800', color: palette.gold },
    downloadBtn: { marginTop: 8 },
  });
}
