// src/screens/tabs/partnersStyles.ts
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    flexDirection: 'row',
  },
  rootGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  rootGlowTop: {
    position: 'absolute',
    top: -90,
    left: 30,
    width: 210,
    height: 210,
    borderRadius: 105,
    opacity: 0.2,
  },
  rootGlowBottom: {
    position: 'absolute',
    right: -80,
    bottom: -60,
    width: 240,
    height: 240,
    borderRadius: 120,
    opacity: 0.18,
  },

  appLaunchBar: {
    position: 'absolute',
    right: 24,
    bottom: 40,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    zIndex: 99,
  },
  appLaunchButton: {
    borderWidth: 2,
    borderRadius: 16,
    paddingHorizontal: 2,
    paddingVertical: 2,
    position: 'relative',
    minWidth: 54,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  appLaunchButtonInner: {
    width: 50,
    height: 50,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appLaunchIcon: {
    width: 20,
    height: 20,
  },
  appLaunchBadge: {
    position: 'absolute',
    top: -7,
    right: -7,
    minWidth: 20,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },

  // LEFT RAIL
  leftRail: {
    flexDirection: 'column',
    paddingVertical: 12,
    alignItems: 'center',
    borderRightWidth: 1,
  },
  addPartnerButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 5,
  },
  partnerList: {
    alignItems: 'center',
    paddingVertical: 2,
  },
  partnerAvatarWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    overflow: 'hidden',
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  partnerAvatarImage: {
    width: '100%',
    height: '100%',
  },
  partnerAvatarInner: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  partnerAvatarActiveRail: {
    position: 'absolute',
    left: 0,
    top: 10,
    width: 4,
    height: 28,
    borderRadius: 2,
    zIndex: 2,
  },
  // CENTER
  centerPane: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  centerScrollContent: {
    paddingBottom: 42,
  },
  partnerHeader: {
    marginBottom: 16,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  partnerHeaderGradient: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    minHeight: 126,
  },
  partnerHeaderAccent: {
    position: 'absolute',
    right: -30,
    top: -46,
    width: 150,
    height: 150,
    borderRadius: 75,
    opacity: 0.2,
  },
  partnerHeaderKicker: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  partnerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  partnerHeaderIdentity: {
    flex: 1,
    minWidth: 0,
  },
  partnerHeroAvatar: {
    width: 54,
    height: 54,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  partnerName: {
    flex: 1,
    fontSize: 24,
    fontWeight: '900',
    marginRight: 8,
  },
  partnerTagline: {
    fontSize: 13,
    marginTop: 6,
    lineHeight: 18,
  },
  partnerHeaderMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  partnerHeaderPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
  },
  partnerHeaderPillText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0,
  },

  // Admins
  adminsSection: {
    marginBottom: 16,
  },
  adminsLabel: {
    fontSize: 12,
    marginBottom: 8,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  adminsList: {
    paddingVertical: 2,
  },
  adminCard: {
    width: 90,
    marginRight: 10,
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderRadius: 14,
    borderWidth: 1,
  },
  adminAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
  },

  // Sections
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  sectionHeaderText: {
    fontSize: 16,
    fontWeight: '900',
  },
  sectionHeaderMeta: {
    fontSize: 12,
    fontWeight: '700',
  },
  groupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: 1,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  groupHash: {
    width: 28,
    height: 28,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },

  // Communities
  communityCard: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginTop: 10,
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  communityHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  communityGroupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 12,
    marginBottom: 6,
    marginLeft: 4,
    borderWidth: 1,
  },

  // RIGHT MESSAGES PANE
  messagesPane: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    borderLeftWidth: 1,
    zIndex: 20,
    elevation: 4,
  },
  messagesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
  },
  toggleButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  messagesPeekToggle: {
    position: 'absolute',
    right: 20,
    top: 8,
    zIndex: 2,
  },
  messagesTitleWrap: {
    flex: 1,
  },
  messagesTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  messagesSubtitle: {
    fontSize: 12,
    marginTop: 2,
  },
  messagesBody: {
    flex: 1,
    paddingVertical: 8,
  },
  messagesPlaceholderTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  messagesPlaceholderText: {
    fontSize: 13,
    lineHeight: 18,
  },

  // PARTNER SETTINGS BOTTOM SHEET
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 20,
    elevation: 6,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 16,
    shadowOpacity: 0.22,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -12 },
    elevation: 14,
  },
  sheetDragZone: {
    paddingTop: 4,
    paddingBottom: 12,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 48,
    height: 4,
    borderRadius: 2,
    marginBottom: 10,
  },
  sheetTitle: {
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  sheetSubtitle: {
    fontSize: 13,
    marginBottom: 12,
  },
  sheetSection: {
    marginBottom: 12,
  },
  sheetSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  sheetSectionText: {
    fontSize: 13,
    lineHeight: 18,
  },

  // PARTNER SETTINGS SHEET
  settingsScrollContent: {
    paddingBottom: 44,
  },
  settingsSheetHeader: {
    paddingHorizontal: 2,
    paddingTop: 2,
    paddingBottom: 14,
  },
  settingsHeroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  settingsHeroTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  settingsEyebrow: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0,
    marginBottom: 6,
  },
  settingsTitle: {
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 29,
  },
  settingsSubtitle: {
    fontSize: 13,
    marginTop: 8,
    lineHeight: 18,
  },
  settingsCloseButton: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  settingsCloseText: {
    fontSize: 12,
    fontWeight: '800',
  },
  settingsHeroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  settingsRoleBadge: {
    alignSelf: 'flex-start',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'transparent',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  settingsRoleText: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
  },
  settingsStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  settingsStatCard: {
    width: '48%',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  settingsStatValue: {
    fontSize: 22,
    fontWeight: '900',
  },
  settingsStatLabel: {
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  settingsQuickActionPanel: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    marginBottom: 14,
  },
  settingsActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  settingsAreasHeader: {
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  settingsSectionCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    marginBottom: 12,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  settingsSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  settingsSectionTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
  },
  settingsSectionMeta: {
    fontSize: 11,
    fontWeight: '900',
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  settingsSectionDescription: {
    fontSize: 12,
    lineHeight: 17,
  },
  settingsSectionActionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },

  // SETTINGS PANEL
  settingsPanelOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    left: 0,
    zIndex: 40,
    elevation: 6,
  },
  settingsPanelBackdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  settingsPanelContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    left: 0,
    borderLeftWidth: 1,
  },
  settingsPanelHeader: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  settingsPanelTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  settingsPanelDescription: {
    fontSize: 12,
    marginTop: 2,
  },
  settingsPanelBody: {
    padding: 16,
  },
  settingsFeatureRow: {
    borderRadius: 10,
    borderWidth: 2,
    padding: 10,
    marginBottom: 8,
  },
  settingsFeatureTitle: {
    fontSize: 13,
    fontWeight: '700',
  },
  settingsFeatureDescription: {
    fontSize: 12,
    marginTop: 4,
  },
  settingsFeatureMeta: {
    fontSize: 10,
    fontWeight: '700',
    marginTop: 6,
  },
  settingsTextInput: {
    borderWidth: 2,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 8,
    fontSize: 13,
  },
  overviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  overviewCard: {
    width: '48%',
    borderRadius: 12,
    borderWidth: 2,
    padding: 10,
  },
  overviewValue: {
    fontSize: 18,
    fontWeight: '800',
  },
  overviewLabel: {
    fontSize: 11,
    marginTop: 4,
  },
  overviewMeta: {
    fontSize: 10,
    marginTop: 2,
  },
  insightsBadge: {
    position: 'absolute',
    top: 12,
    right: 16,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    zIndex: 50,
  },
  insightsBadgeText: {
    fontSize: 13,
    fontWeight: '700',
  },
});

export default styles;
