const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'src', 'env.ts');

const parseEnv = (source) => {
  const values = {};
  source.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eq = trimmed.indexOf('=');
    if (eq < 0) return;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  });
  return values;
};

const defaults = {
  KIS_ENV: 'local',
  KIS_USE_LOCAL_BACKENDS: 'true',
  KIS_DEV_BACKEND_HOST: '',
  KIS_DJANGO_BASE_URL: '',
  KIS_NEST_BASE_URL: '',
  KIS_CHAT_WS_URL: '',
  KIS_CHAT_WS_PATH: '/ws',
  KIS_MEDIA_VERIFICATION_ENABLED: 'false',
};

const env = fs.existsSync(envPath)
  ? { ...defaults, ...parseEnv(fs.readFileSync(envPath, 'utf8')) }
  : defaults;

const pick = (key) => JSON.stringify(String(env[key] ?? ''));

const output = `// Generated by scripts/sync-env.cjs from .env.
// Do not put secrets here. React Native bundles this file into the app.

export const APP_ENV = {
  KIS_ENV: ${pick('KIS_ENV')},
  KIS_USE_LOCAL_BACKENDS: ${pick('KIS_USE_LOCAL_BACKENDS')},
  KIS_DEV_BACKEND_HOST: ${pick('KIS_DEV_BACKEND_HOST')},
  KIS_DJANGO_BASE_URL: ${pick('KIS_DJANGO_BASE_URL')},
  KIS_NEST_BASE_URL: ${pick('KIS_NEST_BASE_URL')},
  KIS_CHAT_WS_URL: ${pick('KIS_CHAT_WS_URL')},
  KIS_CHAT_WS_PATH: ${pick('KIS_CHAT_WS_PATH')},
  KIS_MEDIA_VERIFICATION_ENABLED: ${pick('KIS_MEDIA_VERIFICATION_ENABLED')},
} as const;
`;

fs.writeFileSync(outPath, output);
console.log(`[env] wrote ${path.relative(root, outPath)} from ${fs.existsSync(envPath) ? '.env' : 'defaults'}`);
