// Generated by scripts/sync-env.cjs from .env.
// Do not put secrets here. React Native bundles this file into the app.

export const APP_ENV = {
  KIS_ENV: "local",
  KIS_USE_LOCAL_BACKENDS: "true",
  KIS_DEV_BACKEND_HOST: "",
  KIS_DJANGO_BASE_URL: "",
  KIS_NEST_BASE_URL: "",
  KIS_CHAT_WS_URL: "",
  KIS_CHAT_WS_PATH: "/ws",
  KIS_MEDIA_VERIFICATION_ENABLED: "false",
} as const;
