// Generated by scripts/sync-env.cjs from .env.
// Do not put secrets here. React Native bundles this file into the app.

export const APP_ENV = {
  KIS_ENV: "local",
  KIS_USE_LOCAL_BACKENDS: "true",
  KIS_DEV_BACKEND_HOST: "192.168.0.2",
  KIS_DJANGO_BASE_URL: "",
  KIS_NEST_BASE_URL: "https://chat.kingdomimpactventures.org",
  KIS_CHAT_WS_URL: "wss://chat.kingdomimpactventures.org",
  KIS_CHAT_WS_PATH: "/ws",
  KIS_MEDIA_VERIFICATION_ENABLED: "true",
  KIS_EDU_V2: "false",
  KIS_PHONE_VERIFICATION_ENABLED: "false",
  KIS_AUTH_RECOVERY_ENABLED: "true",
  KIS_AUTH_LINK_ENABLED: "false",
  KIS_AUTH_REGISTRATION_ENABLED: "false",
} as const;
